file_format: "1"
id: charybdis
name: Charybdis
type: shield
url: https://github.com/jimmerricks/swoop
requires: [pro_micro]
features:
  - keys
  - pointer
siblings:
  - charybdis_left
  - charybdis_right